#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>
static int kmul(int a,int b){int r=0;while(b){if(b&1)r^=a;b>>=1;a<<=1;if(a&16)a^=31;}return r&15;}
static int smul(int a,int x){return kmul(a,x&15)|(kmul(a,x>>4)<<4);}
static constexpr std::array<int,5>H{{1,2,4,8,15}};static constexpr std::array<int,10>NONH{{3,5,6,7,9,10,11,12,13,14}};
struct Desc{uint8_t c=0,n=0;std::array<uint8_t,4>i{},a{};};
static std::vector<int> allrep(){std::array<char,256>s{};std::vector<int>r;for(int x=1;x<256;x++)if(!s[x]){std::vector<int>o;for(int h:H){int y=smul(h,x);s[y]=1;o.push_back(y);}std::sort(o.begin(),o.end());r.push_back(o[0]);}return r;}static std::vector<int> ureps(){auto r=allrep();std::vector<int>u;for(int x:r)if(x!=1&&x!=16)u.push_back(x);return u;}static int canonK(int x){int r=999;for(int a=1;a<16;a++)r=std::min(r,smul(a,x));return r;}
static std::vector<Desc> descriptors(){auto u=ureps();std::array<int,256>k{},ii{},aa{},fx{};k.fill(-1);k[0]=0;for(int h:H){int x=smul(h,1);k[x]=0;fx[x]=x;x=smul(h,16);k[x]=0;fx[x]=x;}for(int i=0;i<49;i++)for(int h:H){int x=smul(h,u[i]);k[x]=1;ii[x]=i;aa[x]=h;}std::vector<Desc>d;d.reserve(138176);for(int x=0;x<256;x++)for(int y=x+1;y<256;y++)for(int z=y+1;z<256;z++){int w=x^y^z;if(w<=z)continue;std::array<int,4>f{{x,y,z,w}},best=f;for(int h:H){std::array<int,4>g;for(int q=0;q<4;q++)g[q]=smul(h,f[q]);std::sort(g.begin(),g.end());best=std::min(best,g);}if(f!=best)continue;Desc q;std::array<int,49>cs{};for(int p:f){if(k[p]==0)q.c^=fx[p];else cs[ii[p]]^=aa[p];}for(int j=0;j<49;j++)if(cs[j]){q.i[q.n]=j;q.a[q.n]=cs[j];q.n++;}if(!q.n||q.n>4)throw std::runtime_error("bad desc");d.push_back(q);}if(d.size()!=138176)throw std::runtime_error("bad desc count");return d;}
using Form=std::array<uint64_t,7>;struct FH{size_t operator()(Form const&f)const noexcept{uint64_t h=0x9e3779b97f4a7c15ULL;for(auto x:f)h^=x+0x9e3779b97f4a7c15ULL+(h<<6)+(h>>2);return h;}};static Form one(int v){Form f{};f[(v-1)>>6]|=1ULL<<((v-1)&63);return f;}static Form xo(Form a,const Form&b){for(int i=0;i<7;i++)a[i]^=b[i];return a;}static int pop(const Form&f){int n=0;for(auto x:f)n+=__builtin_popcountll(x);return n;}
class Out{std::ofstream b;int next;uint64_t lines=0,xors=0,cnfs=0;std::unordered_map<Form,int,FH>cache;public:Out(std::string p,int first):b(p,std::ios::binary),next(first){cache.reserve(1500000);}int lin(const Form&f){int n=pop(f);if(!n)return 0;if(n==1){for(int w=0;w<7;w++)if(f[w])return 1+64*w+__builtin_ctzll(f[w]);}auto it=cache.find(f);if(it!=cache.end())return it->second;int z=next++;cache.emplace(f,z);b<<"x "<<-z<<' ';for(int w=0;w<7;w++){uint64_t x=f[w];while(x){int q=__builtin_ctzll(x);x&=x-1;b<<1+64*w+q<<' ';}}b<<"0\n";lines++;xors++;return z;}void cl(std::vector<int>v){if(v.empty())throw std::runtime_error("empty");for(int x:v)b<<x<<' ';b<<"0\n";lines++;cnfs++;}void close(){b.close();}int vars()const{return next-1;}uint64_t nlines()const{return lines;}uint64_t nx()const{return xors;}uint64_t nc()const{return cnfs;}size_t forms()const{return cache.size();}};
static int pvar(int i,int b){return 1+8*i+b;}static int col(int f,int c){return 393+3*f+c;}
int main(int ac,char**av)try{std::string outp=ac>1?av[1]:"class22.xcnf",tmp=outp+".body";auto ds=descriptors();auto full=allrep();auto u=ureps();std::array<int,256>ui{},fi{};ui.fill(-1);fi.fill(-1);for(int i=0;i<49;i++)ui[u[i]]=i;for(int i=0;i<51;i++)fi[full[i]]=i;std::array<std::array<Form,8>,49*16>LF{};for(int i=0;i<49;i++)for(int a=1;a<16;a++)for(int sb=0;sb<8;sb++){int y=smul(a,1<<sb);for(int b=0;b<8;b++)if(y>>b&1)LF[i*16+a][b]=xo(LF[i*16+a][b],one(pvar(i,sb)));}
 Out o(tmp,546);uint64_t nd=0,np=0,nci=0,nco=0,na=0;std::vector<int>forb{0};for(int h:H){forb.push_back(smul(h,1));forb.push_back(smul(h,16));}std::sort(forb.begin(),forb.end());forb.erase(std::unique(forb.begin(),forb.end()),forb.end());for(int i=0;i<49;i++)for(int x:forb){std::vector<int>c;for(int b=0;b<8;b++)c.push_back((x>>b&1)?-pvar(i,b):pvar(i,b));o.cl(c);nd++;}
 for(int i=0;i<49;i++)for(int j=i+1;j<49;j++)for(int h:H){std::vector<int>c;for(int b=0;b<8;b++)c.push_back(o.lin(xo(one(pvar(i,b)),LF[j*16+h][b])));o.cl(c);np++;}
 std::map<int,std::vector<int>>grp;for(int f=0;f<51;f++)grp[canonK(full[f])].push_back(f);for(int f=0;f<51;f++){o.cl({col(f,0),col(f,1),col(f,2)});nci++;for(int a=0;a<3;a++)for(int b=a+1;b<3;b++){o.cl({-col(f,a),-col(f,b)});nci++;}}for(auto&kv:grp){auto&g=kv.second;if(g.size()!=3)throw std::runtime_error("line");for(int c=0;c<3;c++){o.cl({col(g[0],c),col(g[1],c),col(g[2],c)});nci++;for(int a=0;a<3;a++)for(int b=a+1;b<3;b++){o.cl({-col(g[a],c),-col(g[b],c)});nci++;}}}o.cl({col(fi[1],0)});o.cl({col(fi[16],0)});o.cl({col(fi[3],1)});nci+=3;
 auto fb=[&](int f){return full[f]==1?1:full[f]==16?16:-1;};auto ux=[&](int f){if(ui[full[f]]<0)throw std::runtime_error("ux");return ui[full[f]];};for(int l=0;l<51;l++)for(int r=l+1;r<51;r++)for(int a:NONH){int lc=fb(l),rc=fb(r);if(lc>=0&&rc>=0)continue;std::vector<int>bits;for(int b=0;b<8;b++){Form f{};int con=0;if(lc>=0){f=LF[ux(r)*16+a][b];con=(lc>>b)&1;}else if(rc>=0){f=one(pvar(ux(l),b));con=(smul(a,rc)>>b)&1;}else f=xo(one(pvar(ux(l),b)),LF[ux(r)*16+a][b]);int v=o.lin(f);bits.push_back(con?-v:v);}for(int c=0;c<3;c++){auto q=bits;q.insert(q.begin(),{-col(l,c),-col(r,c)});o.cl(q);nco++;}}
 for(auto&d:ds){std::vector<int>c;bool taut=false;for(int b=0;b<8;b++){Form f{};for(int q=0;q<d.n;q++)f=xo(f,LF[d.i[q]*16+d.a[q]][b]);int v=o.lin(f),cc=(d.c>>b)&1;if(!v){if(cc){taut=true;break;}}else c.push_back(cc?-v:v);}if(!taut){o.cl(c);na++;}}
 o.close();std::ofstream out(outp,std::ios::binary);out<<"c Class-22 native-XOR edge-coloring instance\n"<<"c x-lines have XOR of listed literals equal to true\n"<<"c domain "<<nd<<" pair "<<np<<" color-input "<<nci<<" color-output "<<nco<<" APN "<<na<<" xor-defs "<<o.nx()<<"\n"<<"p cnf "<<o.vars()<<' '<<o.nlines()<<"\n";std::ifstream in(tmp,std::ios::binary);out<<in.rdbuf();out.close();in.close();std::remove(tmp.c_str());std::cerr<<"vars="<<o.vars()<<" lines="<<o.nlines()<<" xors="<<o.nx()<<" cnf="<<o.nc()<<" forms="<<o.forms()<<"\n";
}catch(std::exception&e){std::cerr<<"fatal "<<e.what()<<'\n';return 2;}
